const predefinedMovies = [
  {
    title: "A City of Sadness",
    imageUrl: "images/A_city_of_sadness.JPG",
    description: "In the face of momentous times, the fate of ordinary people always seems so insignificant that it might as well be ignored. Individuals who bravely stand up to try to stop the torrents of the era often resemble Don Quixote futilely charging at windmills, usually ending up as martyrs, and more often, they don't even have the choice to be bystanders. Yet, the tragedy of ordinary people undoubtedly reflects the absurdity and cruelty of history.",
    moreDescription: "After Japan's unconditional surrender in 1945 and Taiwan's subsequent recovery, a Lin family in Keelung thought they were about to live better days. However, fate had other plans, and the Lin family faced continuous upheavals. After the \"February 28 Incident,\" only the fourth brother, Lin Wenqing (played by Tony Leung), a deaf-mute who owned a photo studio, remained out of trouble. However, the tragedy did not stop there; due to connections with progressive individuals, Lin Wenqing could not escape arrest, leaving only him and his infant nephew, Wu Kuan-mei (played by Hsin Shu-fen), who was still babbling in his cradle."
  },
  {
    title: "The Suspended Step of a Stork",
    imageUrl: "images/The_suspended_step_of_a_stork.JPG",
    description: "The story is set on the Greek border and is said to be a film about the despair of the end of the century. It focuses on the issues of contemporary borders, refugees, and transitions after the decline of Eastern European communism and the dissolution of the Soviet Union.",
    moreDescription: "A politician leaves the parliament and vanishes from his home without a trace. Journalist Gregory Karr is reporting on the immigrants and refugees stuck at the border, where he encounters someone who greatly resembles the missing politician. He also discovers a town split by a river used as a national border, witnessing a surreal wedding with the bride and her family on one side of the river and the groom and his guests on the other. The man's identity remains unconfirmed, and the plight of the unfortunate refugees and the divided village deepens Karr's despair about the human condition."
  },
  {
    title: "Andrei Rublev",
    imageUrl: "images/Andrei_Rublev.jpg",
    description: "At the beginning of the 15th century, during a tumultuous period in Russia, the renowned icon painter Andrei Rublev (portrayed by Anatoli Solonitsyn) is invited to Moscow by the Grand Prince to paint for a church, where he receives aristocratic treatment. However, Rublev finds himself in a tragic era ravaged by Tatar invasions and filled with disaster and slaughter. Witnessing the suffering of the people under the Grand Prince's tyranny, Rublev decisively leaves the church to return to the monastery. Soon, he is forced to return to Moscow to create icons once again. Confronted with the innocent slaughter of the residents and the ruthless destruction of churches during the wars, Rublev falls into a deep questioning of the huge disparity between art and reality, refusing to continue painting. By 1423, the Tatar forces are finally driven out of Russian lands. After enduring trials of fire and blood, Rublev ultimately completes his masterpiece, \"The Trinity.\"",
    moreDescription: "Directed by the Soviet cinematic master Andrei Tarkovsky, the epic film \"Andrei Rublev\" uses Tarkovsky's unique poetic cinematic language and dense, historical mural-like strokes to depict the life of wandering and decisions of the famous 15th-century Russian icon painter Andrei Rublev. The film was awarded the FIPRESCI Prize at the 22nd Cannes Film Festival in 1969."
  },
  {
    title: "Time of the Gypsies",
    imageUrl: "images/Time_of_the_Gypsies.JPG",
    description: "In the village of Ciganska, on the outskirts of a Balkan city, young Behan (played by Davor Dujmovic) lives with his grandmother and four family members, including a gambling-addicted uncle, Mersan, who pines for his past life in Germany and whose losses at the gambling table have left Behan's sister untreated for her leg illness due to lack of money. Behan falls in love with Azna from the same village, but her mother rejects him because of his family's poverty. The tribe leader Amed, who has been earning money in Italy, returns to the village and gambles with Mersan, driving him to insanity and destruction of their wooden hut. However, the grandmother uses witchcraft to save Amed's child, and in gratitude, Amed agrees to take the sister abroad for medical treatment and also takes Behan, who possesses the unusual ability to move small metal objects through the air. Soon, Behan discovers that Amed is just exploiting children for begging and thievery. Despite feeling trapped, Behan takes over the gang when Amed falls ill, quickly becoming wealthy. He then returns to the village to bring Azna to Milan, but his anger erupts when he learns that Azna is pregnant, insisting on selling the child…",
    moreDescription: "This film won the Best Director Award at the Cannes Film Festival in 1989."
  },
  {
    title: "Hill of No Return",
    imageUrl: "images/Hill_of_no_return.JPG",
    description: "In 1927, a flood of impoverished farmers headed to the Jinguashi area in Jiufen, Taiwan, hoping to strike gold and fulfill their dreams. Among them were the simple tenant farmers, the brothers Ah Zhu and Ah Wei, who rented a shabby house from the widow Ah Rou. Ah Rou, known as a woman cursed with the misfortune of outliving her husbands, gradually develops feelings for Ah Zhu amidst the gold rush. The boom brought not only prospectors but also rampant smuggling and prostitution to Jiufen. The Japanese authorities appointed the talented Chaita to manage the order of the gold mines. However, as miners and brothels colluded and gold trading became increasingly uncontrollable, violent conflicts erupted, culminating in the murder of Chaita. Soon after marrying Ah Rou, Ah Zhu dies from illness, leaving Ah Rou tearless and desolate. With her four children and her late husband's memorial tablet in tow, she leaves Jiufen in solitude…",
    moreDescription: ""
  },
  {
    title: "Autumn Sonata",
    imageUrl: "images/Autumn_sonata.JPG",
    description: "Charlotte (played by Ingrid Bergman) is a distinguished pianist in an orchestra, and her daughter Eva (played by Liv Ullmann) is the wife of a pastor working in a rural community. There is a profound emotional rift between them, and they have not communicated in seven years. After learning of the death of Charlotte's second husband, Eva writes to invite Charlotte to stay with her, and both try to get along amicably, but inevitably old grievances resurface. Eva resents Charlotte for not providing her with enough care during her childhood, focusing instead on her career and distancing herself from both Eva and another daughter, Helena (played by Lena Nyman), who has severe disabilities and communicates through unclear sounds. Charlotte, already troubled by her husband's death, finds her mood further darkened by the living arrangement with Helena and Eva.",
    moreDescription: ""
  },
  {
    title: "Mouchette",
    imageUrl: "images/Mouchette.JPG",
    description: "Mouchette (played by Nadine Nortier) is a 14-year-old girl living in the French countryside, experiencing a bleak and difficult childhood. Her father (played by Paul Hebert) is a bootlegger and a drunkard who neglects household responsibilities; her mother (played by Marie Cardinal) is terminally ill and bedridden, awaiting death; and her constantly crying baby brother adds to the household's troubles. The hardships at home force Mouchette to mature prematurely. The money she earns from odd jobs is stolen by her father, who also beats her frequently. At school, she is mocked and bullied by her peers, and the defiant Mouchette vents her frustrations by throwing clods of earth at classmates after school. Her childhood, which should be filled with happiness, withers prematurely...",
    moreDescription: "This film won several awards, including the OCIC Award at the 1967 Cannes Film Festival, the Best Film Award from the French Film Critics Association in 1968, the Silver Ribbon for Best Foreign Director from the Italian Film Journalists Association in 1969, and the Pasinetti Award for Best Film at the 1967 Venice Film Festival."
  },
  {
    title: "A Brighter Summer Day",
    imageUrl: "images/A_brighter_summer_day.JPG",
    description: "Before meeting Xiaoming (played by Yang Jingyi), Xiaosi (played by Zhang Zhen) was the typical good boy, the hope of his parents and the pride of his siblings, with the whole family relying on him to enter a prestigious university to elevate their social status. He had a friend who loved rock music and called himself \"Little Elvis\" (played by Wang Qizan). Although they would go to the woods to watch people in secret rendezvous, their lives were very different from those of many youths hanging around the \"Little Park.\"",
    moreDescription: "After falling for Xiaoming, Xiaosi plunged into a bottomless abyss, increasingly manipulated by various external forces. His new idol, Honey (played by Lin Hongming), dies unexpectedly, and a particular incident severely damages the self-esteem and spirit of his respected father. Coupled with seeing through Xiaoming, who repeatedly \"deceived and toyed\" with his feelings, the morally strong and hot-blooded Xiaosi finally turns to crime, hoping to eradicate the root of his problems with his own hands. However, Xiaosi doesn't realize that what he perceives as the root is merely an insignificant link in a much larger chain."
  },
  {
    title: "Sunrise: A Song of Two Humans",
    imageUrl: "images/Sunrise.JPG",
    description: "During the summer vacation season, a city woman comes to the countryside and stays there, during which time she seduces a local farmer and convinces him to murder his wife (played by Janet Gaynor) so they can sell the farm and elope. The bewitched man forgets the pure moments he once shared with his wife. He takes her to the river with plans to harm her but has a last-minute change of heart. The heartbroken wife boards a train to the city, and the man chases after her, both reaching the city together. The city turns out to be a dazzling world; as the couple roams and has fun in the streets, through small jokes and sweet adventures, they rediscover the wonderful resonance of their love... Reconciled, they return to the countryside but encounter a raging storm on their way back...",
    moreDescription: "This film is the first work of German director Murnau after moving to America, and it has been selected by multiple authoritative media as one of the best silent films ever made. It won several awards at the first Academy Awards, including Best Actress and Cinematography."
  },
  {
    title: "Intolerance",
    imageUrl: "images/Intolerance.JPG",
    description: "This is D.W. Griffith's most ambitiously creative work. Inspired by the astounding box office success of \"The Birth of a Nation,\" Griffith was motivated to create a film with even grander scale and deeper content. He spent a year and a half and $2 million to produce a film originally 480 minutes long, though the final version was cut down to 220 minutes. Unfortunately, when it premiered in New York in September 1916, it did not receive the anticipated reception. The film's box office failure is attributed to several factors, mainly that Griffith's complex narrative structure and directorial techniques surpassed the contemporary audience's understanding. Additionally, its serious themes advocating tolerance and opposing violence clashed with America's heightened wartime sentiments, limiting its appeal. Nevertheless, it remains undeniable that this film is a timeless masterpiece of cinematic art.",
    moreDescription: `“Intolerance” is structured around four distinct historical periods: the fall of Babylon, the crucifixion of Jesus Christ, the St. Bartholomew's Day Massacre in France, and early 20th-century labor conflicts in America. Griffith described his concept as “four great stories that flow together like four streams, initially separate and tranquil, but finally converging into a powerful, turbulent river.” The film begins with a shot of a woman rocking a cradle, accompanied by a Walt Whitman poem that reflects on the perpetual cycle of human passions and joys and sorrows. This sets the tone for the contemporary story that unfolds first. As the plot progresses, Griffith often cuts to the other three stories, developing them in parallel. The film concludes back with the woman and the cradle, symbolizing humanity’s evolution from intolerance to tolerance. The contemporary segment, “Mother and the Law,” describes the plight of four unemployed workers from a small town seeking work in the city, where they face various misadventures and desires for a normal family life. The male protagonist is wrongly accused of murder and sentenced to death, but is saved at the last moment by the real perpetrator’s confession. This narrative reflects the social conditions of early 20th-century America, highlighting rural instability, urban complexity, labor hardships, and legal challenges. Griffith's film innovatively uses “parallel editing” to compare and contrast similar situations across the four storylines, creating a unified and impactful narrative that builds emotional climaxes through repeated scenes. Techniques like moving cameras, cross-cutting, and even brief flashbacks elevate the storytelling, showcasing Griffith’s advanced “film grammar” compared to his contemporaries. Additionally, he introduced close-ups and long shots to enhance the psychological impact on viewers, as well as color tinting for special effects (e.g., blue for night scenes, yellow for lit interiors, and red for the burning of Babylon), a method not invented by Griffith but never used as boldly before in a single film. Remarkably, this complex, large-scale production was created without a complete script, relying instead on Griffith’s improvisational genius. Also, there were no set design plans, yet Griffith managed to construct the impressive Babylon set and coordinated scenes using 15,000 extras and 250 chariots in a single day, surpassing even the grand historical films produced in Italy at the time. Griffith’s own motto, “Art is often revolutionary, explosive, and thunderous,” truly reflects his hands-on approach to artistry, as demonstrated in “Intolerance.”`
  },
  {
    title: "Farewell My Concubine",
    imageUrl: "images/Farewell_my_concubine.JPG",
    description: "Duan Xiaolou (played by Zhang Fengyi) and Cheng Dieyi (played by Leslie Cheung) are sworn brothers who grew up together, with one playing the male roles and the other specializing as the female lead in Chinese opera. They are seamlessly coordinated, particularly famous for their performance in \"Farewell My Concubine,\" which brought them immense fame in Beijing. They vowed to perform this play together for life. However, their understanding of the relationship between drama and life fundamentally differs: Duan Xiaolou recognizes that life is not a stage, whereas Cheng Dieyi blurs the line between his roles and his reality.",
    moreDescription: "When Duan Xiaolou decides it's time to settle down, he marries Juxian (played by Gong Li), a well-known courtesan. Cheng Dieyi sees Juxian as a shameful interloper, turning Duan Xiaolou into a traitor in his eyes. From there, a tumultuous saga of love, hate, and jealousy unfolds around the play \"Farewell My Concubine,\" escalating with the changing tides of the era and ultimately leading to tragedy."
  }
];
